/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

// Login page

export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_AGAIN = 'PASSWORD_RESET_AGAIN';
export const SENT_RESET_PASSWORD_TOKEN = 'SENT_RESET_PASSWORD_TOKEN';
export const RETRY_PASSWORD_REQUEST = 'RETRY_PASSWORD_REQUEST';
export const UPDATE_PHONE_CODE_VALID = 'UPDATE_PHONE_CODE_VALID';
export const CONFIRM_DIGIT_CODE = 'CONFIRM_DIGIT_CODE';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const LOGOUT = 'LOGOUT';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

//Candidates
export const GET_CANDIDATES_REQUEST = 'GET_CANDIDATES_REQUEST';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_FAILED = 'GET_CANDIDATES_FAILED';

export const UPDATE_CANDIDATE_REQUEST = 'UPDATE_CANDIDATE_REQUEST';
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_FAILED = 'UPDATE_CANDIDATE_FAILED';

export const GET_LEADS_REQUEST = 'GET_LEADS_REQUEST';
export const GET_LEADS_SUCCESS = 'GET_LEADS_SUCCESS';
export const GET_LEADS_FAILED = 'GET_LEADS_FAILED';

export const GET_CANDIDATE_MONTHLY_EXPENSES_REQUEST = 'GET_CANDIDATE_MONTHLY_EXPENSES_REQUEST';
export const GET_CANDIDATE_MONTHLY_EXPENSES_SUCCESS = 'GET_CANDIDATE_MONTHLY_EXPENSES_SUCCESS';
export const GET_CANDIDATE_MONTHLY_EXPENSES_FAILED = 'GET_CANDIDATE_MONTHLY_EXPENSES_FAILED';
export const UPDATE_CANDIDATE_MONTHLY_EXPENSES_REQUEST = 'UPDATE_CANDIDATE_MONTHLY_EXPENSES_REQUEST';
export const UPDATE_CANDIDATE_MONTHLY_EXPENSES_SUCCESS = 'UPDATE_CANDIDATE_MONTHLY_EXPENSES_SUCCESS';
export const UPDATE_CANDIDATE_MONTHLY_EXPENSES_FAILED = 'UPDATE_CANDIDATE_MONTHLY_EXPENSES_FAILED';
export const GET_CANDIDATE_INCOME_REQUEST = 'GET_CANDIDATE_INCOME_REQUEST';
export const GET_CANDIDATE_INCOME_SUCCESS = 'GET_CANDIDATE_INCOME_SUCCESS';
export const GET_CANDIDATE_INCOME_FAILED = 'GET_CANDIDATE_INCOME_FAILED';
export const UPDATE_CANDIDATE_INCOME_REQUEST = 'UPDATE_CANDIDATE_INCOME_REQUEST';
export const UPDATE_CANDIDATE_INCOME_SUCCESS = 'UPDATE_CANDIDATE_INCOME_SUCCESS';
export const UPDATE_CANDIDATE_INCOME_FAILED = 'UPDATE_CANDIDATE_INCOME_FAILED';

export const GET_EXPENSE_TYPES_REQUEST = 'GET_EXPENSE_TYPES_REQUEST';
export const GET_EXPENSE_TYPES_SUCCESS = 'GET_EXPENSE_TYPES_SUCCESS';
export const GET_EXPENSE_TYPES_FAILED = 'GET_EXPENSE_TYPES_FAILED';

export const GET_INCOME_TYPES_REQUEST = 'GET_INCOME_TYPES_REQUEST';
export const GET_INCOME_TYPES_SUCCESS = 'GET_INCOME_TYPES_SUCCESS';
export const GET_INCOME_TYPES_FAILED = 'GET_INCOME_TYPES_FAILED';

export const VALIDATE_PHONE_CODE = 'VALIDATE_PHONE_CODE';
export const VALIDATE_RESET_PASSWORD = 'VALIDATE_RESET_PASSWORD';
export const ACCEPT_NEW_PASSWORD = 'ACCEPT_NEW_PASSWORD';

// Candidate - WORK AND FINANCES
export const SET_WORK_AND_FINANCES = 'SET_WORK_AND_FINANCES';
export const GET_EMPLOYMENTS = 'GET_EMPLOYMENTS';
