export default {
  data: [
    {
      debt_name: 'SYNCB/ONDC',
      creditor: 'SYNCB/ONDC',
      type: 'Credit Card',
      ecoa: 'Individual',
      push: 'No',
      account_number: '1234567890',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '0',
      days_late: '116',
      balance_og: '$3,500.00',
      payment: '$120.00',
      last_collector: 'Add Collector',
      credit_limit: '$500.00',
      graduation: '10/30/23',
      last_update: ''
    },
    {
      debt_name: 'SYNCB/AMEG D',
      creditor: 'SYNCB/AMEG D',
      type: 'Charge Account',
      ecoa: 'Authorized User',
      push: 'No',
      account_number: '2321321334',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '0',
      days_late: '134',
      balance_og: '$1,500.00',
      payment: '$80.00',
      last_collector: 'Add Collector',
      credit_limit: '$3000.00',
      graduation: '10/30/23',
      last_update: ''
    },
    {
      debt_name: 'CCB/ANNTYLR1',
      creditor: 'CCB/ANNTYLR1',
      type: 'Credit Card',
      ecoa: 'Authorized User',
      push: 'No',
      account_number: '543532342',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '30',
      days_late: '122',
      balance_og: '$5,500.00',
      payment: '$120.00',
      last_collector: 'Add Collector',
      credit_limit: '$500.00',
      graduation: '10/30/23',
      last_update: ''
    },
    {
      debt_name: 'BK OF AMER',
      creditor: 'BK OF AMER',
      type: 'Credit Card',
      ecoa: 'Individual',
      push: 'No',
      account_number: '1234567890',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '90',
      days_late: '116',
      balance_og: '$2,500.00',
      payment: '$120.00',
      last_collector: 'Add Collector',
      credit_limit: '$500.00',
      graduation: '10/30/23',
      last_update: ''
    },
    {
      debt_name: 'SYNCB/ONDC',
      creditor: 'SYNCB/ONDC',
      type: 'Charge Account',
      ecoa: 'Individual',
      push: 'No',
      account_number: '2367886654',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '150',
      days_late: '111',
      balance_og: '$2,500.00',
      payment: '$120.00',
      last_collector: 'Add Collector',
      credit_limit: '$1,000',
      graduation: '10/30/23',
      last_update: ''
    },
    {
      debt_name: 'CCB/ANNTYLR1',
      creditor: 'CCB/ANNTYLR1',
      type: 'Charge Account',
      ecoa: 'Individual',
      push: 'No',
      account_number: '7654345678',
      collector_account_number: '123232142',
      last_debt_status: 'Wait for confirm',
      bureaus: '',
      days_delinquent: '180',
      days_late: '104',
      balance_og: '$300.00',
      payment: '$50.00',
      last_collector: 'Add Collector',
      credit_limit: '$500.00',
      graduation: '10/30/23',
      last_update: ''
    }
  ]
};
